#include "kind.hpp"

#include <array>
#include <utility>

namespace baba::core {

namespace {

struct Entry { std::string_view name; Kind kind; };

constexpr std::array kTable = {
    Entry{"baba",   Kind::N_Baba},
    Entry{"wall",   Kind::N_Wall},
    Entry{"flag",   Kind::N_Flag},
    Entry{"rock",   Kind::N_Rock},
    Entry{"water",  Kind::N_Water},
    Entry{"lava",   Kind::N_Lava},
    Entry{"skull",  Kind::N_Skull},
    Entry{"door",   Kind::N_Door},
    Entry{"key",    Kind::N_Key},
    Entry{"keke",   Kind::N_Keke},
    Entry{"fofo",   Kind::N_Fofo},
    Entry{"me",     Kind::N_Me},
    Entry{"box",    Kind::N_Box},
    Entry{"leaf",   Kind::N_Leaf},
    Entry{"cloud",  Kind::N_Cloud},
    Entry{"sun",    Kind::N_Sun},
    Entry{"moon",   Kind::N_Moon},
    Entry{"star",   Kind::N_Star},
    Entry{"planet", Kind::N_Planet},
    Entry{"bolt",   Kind::N_Bolt},
    Entry{"love",   Kind::N_Love},
    Entry{"bomb",   Kind::N_Bomb},
    Entry{"wind",   Kind::N_Wind},
    Entry{"track",  Kind::N_Track},
    Entry{"belt",    Kind::N_Belt},
    Entry{"algae",   Kind::N_Algae},   Entry{"arm",     Kind::N_Arm},
    Entry{"arrow",   Kind::N_Arrow},   Entry{"badbad",  Kind::N_Badbad},
    Entry{"banana",  Kind::N_Banana},  Entry{"bat",     Kind::N_Bat},
    Entry{"bean",    Kind::N_Bean},    Entry{"bed",     Kind::N_Bed},
    Entry{"bee",     Kind::N_Bee},     Entry{"bird",    Kind::N_Bird},
    Entry{"blob",    Kind::N_Blob},    Entry{"boat",    Kind::N_Boat},
    Entry{"boba",    Kind::N_Boba},    Entry{"bog",     Kind::N_Bog},
    Entry{"bone",    Kind::N_Bone},    Entry{"book",    Kind::N_Book},
    Entry{"bottle",  Kind::N_Bottle},  Entry{"brain",   Kind::N_Brain},
    Entry{"brick",   Kind::N_Brick},   Entry{"bubble",  Kind::N_Bubble},
    Entry{"bucket",  Kind::N_Bucket},  Entry{"bug",     Kind::N_Bug},
    Entry{"bunny",   Kind::N_Bunny},   Entry{"burger",  Kind::N_Burger},
    Entry{"cactus",  Kind::N_Cactus},  Entry{"cake",    Kind::N_Cake},
    Entry{"car",     Kind::N_Car},     Entry{"cart",    Kind::N_Cart},
    Entry{"cash",    Kind::N_Cash},    Entry{"cat",     Kind::N_Cat},
    Entry{"chair",   Kind::N_Chair},   Entry{"cheese",  Kind::N_Cheese},
    Entry{"chili",   Kind::N_Chili},   Entry{"circle",  Kind::N_Circle},
    Entry{"cliff",   Kind::N_Cliff},   Entry{"clock",   Kind::N_Clock},
    Entry{"cog",     Kind::N_Cog},     Entry{"crab",    Kind::N_Crab},
    Entry{"crystal", Kind::N_Crystal}, Entry{"cup",     Kind::N_Cup},
    Entry{"dog",     Kind::N_Dog},     Entry{"donut",   Kind::N_Donut},
    Entry{"dot",     Kind::N_Dot},     Entry{"drink",   Kind::N_Drink},
    Entry{"drum",    Kind::N_Drum},    Entry{"dust",    Kind::N_Dust},
    Entry{"ear",     Kind::N_Ear},     Entry{"egg",     Kind::N_Egg},
    Entry{"eye",     Kind::N_Eye},     Entry{"fence",   Kind::N_Fence},
    Entry{"fire",    Kind::N_Fire},    Entry{"fish",    Kind::N_Fish},
    Entry{"flower",  Kind::N_Flower},  Entry{"foliage", Kind::N_Foliage},
    Entry{"foot",    Kind::N_Foot},    Entry{"fort",    Kind::N_Fort},
    Entry{"fox",     Kind::N_Fox},     Entry{"frog",    Kind::N_Frog},
    Entry{"fruit",   Kind::N_Fruit},   Entry{"fungi",   Kind::N_Fungi},
    Entry{"fungus",  Kind::N_Fungus},  Entry{"gate",    Kind::N_Gate},
    Entry{"gem",     Kind::N_Gem},     Entry{"ghost",   Kind::N_Ghost},
    Entry{"grass",   Kind::N_Grass},   Entry{"guitar",  Kind::N_Guitar},
    Entry{"hand",    Kind::N_Hand},    Entry{"hedge",   Kind::N_Hedge},
    Entry{"hihat",   Kind::N_Hihat},   Entry{"hotdog",  Kind::N_Hotdog},
    Entry{"house",   Kind::N_House},   Entry{"husk",    Kind::N_Husk},
    Entry{"husks",   Kind::N_Husks},   Entry{"ice",     Kind::N_Ice},
    Entry{"it",      Kind::N_It},      Entry{"jelly",   Kind::N_Jelly},
    Entry{"jiji",    Kind::N_Jiji},    Entry{"knight",  Kind::N_Knight},
    Entry{"ladder",  Kind::N_Ladder},  Entry{"lamp",    Kind::N_Lamp},
    Entry{"lever",   Kind::N_Lever},   Entry{"lift",    Kind::N_Lift},
    Entry{"lily",    Kind::N_Lily},    Entry{"line",    Kind::N_Line},
    Entry{"lizard",  Kind::N_Lizard},  Entry{"lock",    Kind::N_Lock},
    Entry{"mirror",  Kind::N_Mirror},  Entry{"monitor", Kind::N_Monitor},
    Entry{"monster", Kind::N_Monster}, Entry{"no",      Kind::N_No},
    Entry{"nose",    Kind::N_Nose},    Entry{"orb",     Kind::N_Orb},
    Entry{"palm",    Kind::N_Palm},    Entry{"pants",   Kind::N_Pants},
    Entry{"paper",   Kind::N_Paper},   Entry{"pawn",    Kind::N_Pawn},
    Entry{"piano",   Kind::N_Piano},   Entry{"pillar",  Kind::N_Pillar},
    Entry{"pipe",    Kind::N_Pipe},    Entry{"pixel",   Kind::N_Pixel},
    Entry{"pizza",   Kind::N_Pizza},   Entry{"plane",   Kind::N_Plane},
    Entry{"plank",   Kind::N_Plank},   Entry{"potato",  Kind::N_Potato},
    Entry{"pumpkin", Kind::N_Pumpkin}, Entry{"reed",    Kind::N_Reed},
    Entry{"ring",    Kind::N_Ring},    Entry{"road",    Kind::N_Road},
    Entry{"robot",   Kind::N_Robot},   Entry{"rocket",  Kind::N_Rocket},
    Entry{"rose",    Kind::N_Rose},    Entry{"rubble",  Kind::N_Rubble},
    Entry{"sax",     Kind::N_Sax},     Entry{"scissors",Kind::N_Scissors},
    Entry{"seed",    Kind::N_Seed},    Entry{"shell",   Kind::N_Shell},
    Entry{"shirt",   Kind::N_Shirt},   Entry{"shovel",  Kind::N_Shovel},
    Entry{"sign",    Kind::N_Sign},    Entry{"snail",   Kind::N_Snail},
    Entry{"spike",   Kind::N_Spike},   Entry{"sprout",  Kind::N_Sprout},
    Entry{"square",  Kind::N_Square},  Entry{"statue",  Kind::N_Statue},
    Entry{"stick",   Kind::N_Stick},   Entry{"stump",   Kind::N_Stump},
    Entry{"sword",   Kind::N_Sword},   Entry{"table",   Kind::N_Table},
    Entry{"teeth",   Kind::N_Teeth},   Entry{"tile",    Kind::N_TileObj},
    Entry{"tower",   Kind::N_Tower},   Entry{"train",   Kind::N_Train},
    Entry{"tree",    Kind::N_Tree},    Entry{"trees",   Kind::N_Trees},
    Entry{"triangle",Kind::N_Triangle},Entry{"trumpet", Kind::N_Trumpet},
    Entry{"turnip",  Kind::N_Turnip},  Entry{"turtle",  Kind::N_Turtle},
    Entry{"ufo",     Kind::N_Ufo},     Entry{"vase",    Kind::N_Vase},
    Entry{"vine",    Kind::N_Vine},    Entry{"what",    Kind::N_What},
    Entry{"worm",    Kind::N_Worm},    Entry{"yes",     Kind::N_Yes},
    Entry{"text",    Kind::N_Text},

    Entry{"is",       Kind::O_Is},
    Entry{"and",      Kind::O_And},
    Entry{"not",      Kind::O_Not},
    Entry{"on",       Kind::O_On},
    Entry{"make",     Kind::O_Make},
    Entry{"eat",      Kind::O_Eat},
    Entry{"facing",   Kind::O_Facing},
    Entry{"has",      Kind::O_Has},
    Entry{"powered",  Kind::O_Powered},
    Entry{"powered2", Kind::O_Powered2},
    Entry{"powered3", Kind::O_Powered3},
    Entry{"follow",   Kind::O_Follow},
    Entry{"fear",     Kind::O_Fear},
    Entry{"play",     Kind::O_Play},
    // PLAY parameter tokens
    Entry{"a", Kind::O_LetterA}, Entry{"b", Kind::O_LetterB}, Entry{"c", Kind::O_LetterC},
    Entry{"d", Kind::O_LetterD}, Entry{"e", Kind::O_LetterE}, Entry{"f", Kind::O_LetterF},
    Entry{"g", Kind::O_LetterG}, Entry{"h", Kind::O_LetterH}, Entry{"i", Kind::O_LetterI},
    Entry{"j", Kind::O_LetterJ}, Entry{"k", Kind::O_LetterK}, Entry{"l", Kind::O_LetterL},
    Entry{"m", Kind::O_LetterM}, Entry{"n", Kind::O_LetterN}, Entry{"o", Kind::O_LetterO},
    Entry{"p", Kind::O_LetterP}, Entry{"q", Kind::O_LetterQ}, Entry{"r", Kind::O_LetterR},
    Entry{"s", Kind::O_LetterS}, Entry{"t", Kind::O_LetterT}, Entry{"u", Kind::O_LetterU},
    Entry{"v", Kind::O_LetterV}, Entry{"w", Kind::O_LetterW}, Entry{"x", Kind::O_LetterX},
    Entry{"y", Kind::O_LetterY}, Entry{"z", Kind::O_LetterZ},
    Entry{"sharp", Kind::O_Sharp},
    Entry{"flat",  Kind::O_Flat},
    Entry{"0", Kind::O_Num0}, Entry{"1", Kind::O_Num1}, Entry{"2", Kind::O_Num2},
    Entry{"3", Kind::O_Num3}, Entry{"4", Kind::O_Num4}, Entry{"5", Kind::O_Num5},
    Entry{"6", Kind::O_Num6}, Entry{"7", Kind::O_Num7}, Entry{"8", Kind::O_Num8},
    Entry{"9", Kind::O_Num9},

    Entry{"you",    Kind::P_You},
    Entry{"push",   Kind::P_Push},
    Entry{"stop",   Kind::P_Stop},
    Entry{"win",    Kind::P_Win},
    Entry{"defeat", Kind::P_Defeat},
    Entry{"sink",   Kind::P_Sink},
    Entry{"hot",    Kind::P_Hot},
    Entry{"melt",   Kind::P_Melt},
    Entry{"open",   Kind::P_Open},
    Entry{"shut",   Kind::P_Shut},
    Entry{"move",      Kind::P_Move},
    Entry{"weak",      Kind::P_Weak},
    Entry{"auto",      Kind::P_Auto},
    Entry{"fall",      Kind::P_Fall},
    Entry{"fallup",    Kind::P_Fallup},
    Entry{"fallleft",  Kind::P_Fallleft},
    Entry{"fallright", Kind::P_Fallright},
    Entry{"left",      Kind::P_Left},
    Entry{"right",     Kind::P_Right},
    Entry{"up",        Kind::P_Up},
    Entry{"down",      Kind::P_Down},
    Entry{"still",     Kind::P_Still},
    Entry{"shift",     Kind::P_Shift},
    Entry{"swap",        Kind::P_Swap},
    Entry{"revert",      Kind::P_Revert},
    Entry{"nudgeright",  Kind::P_Nudgeright},
    Entry{"nudgeup",     Kind::P_Nudgeup},
    Entry{"nudgeleft",   Kind::P_Nudgeleft},
    Entry{"nudgedown",   Kind::P_Nudgedown},
    Entry{"power",       Kind::P_Power},
    Entry{"power2",      Kind::P_Power2},
    Entry{"power3",      Kind::P_Power3},
};

}  // namespace

std::string_view kind_name(Kind k) {
    for (auto const& e : kTable) {
        if (e.kind == k) return e.name;
    }
    return "?";
}

std::optional<Kind> kind_from_name(std::string_view name) {
    for (auto const& e : kTable) {
        if (e.name == name) return e.kind;
    }
    return std::nullopt;
}

}  // namespace baba::core
